# Generated by Django 4.2.4 on 2023-09-01 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='starting_bid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
