# Generated by Django 4.2.5 on 2023-09-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "auctions",
            "0004_alter_listing_description_alter_listing_starting_bid_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
