# Generated by Django 4.2.4 on 2023-10-30 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_comment_listing_comment_text_comment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 30, 15, 8, 39, 987151)),
        ),
    ]
